backend:
  name: github
  repo: WYPPUG/Website
  branch: netlify-cms-extension
  site_domain: wyppug.org.uk
  open_authoring: true

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

logo_url: /images/logo-wide.png

collections:
  - name: pages
    label: Pages
    folder: src/pages
    extension: mdx
    format: frontmatter
    create: true
    delete: true
    summary: "{{title}}"
    fields:
      - { name: title, label: title }
      - { name: body, label: Body, widget: markdown }
  - name: events
    label: Events
    folder: src/pages/events
    extension: mdx
    format: frontmatter
    create: true
    delete: true
    sortable_fields: ['title', 'startDate']
    summary: "{{startDate}} - {{title}}"
    view_groups:
      - label: Year
        field: startDate
        pattern: \d{4}
    fields:
      - { name: title, label: Title }
      - { name: startDate, label: Start Date, widget: datetime }
      - { name: endDate, label: End Date, widget: datetime }
      - { name: displayDate, label: Display Date, required: false }
      - { name: location, label: Location }
      - { name: summary, label: Summary }
      - { name: body, label: Body, widget: markdown }
      - name: preMeetingLinks
        label: "Pre-meeting links"
        required: false
        widget: list
        summary: "{{name}} - {{url}}"
        fields: 
          - {label: Name, name: name}
          - {label: URL, name: url, required: false}
      - name: postMeetingLinks
        label: "Post-meeting links"
        required: false
        widget: list
        summary: "{{name}} - {{url}}"
        fields: 
          - {label: Name, name: name}
          - {label: URL, name: url, required: false}
           